### PR TITLE
Fix CSS identation and add some semicolumns in css

### PR DESCRIPTION
**Pull request by pivanov**

### CODE REVIEW

**Comment by etiennesegonzac** [comment]
Quick and simple first contribution, welcome :)

**Comment by pivanov** [comment]
thanks :)

**Comment by jonathanKingston** [comment]
@pivanov I wasn't able to test at the time but I have a feeling the homescreen stuff may no longer being applied on android anyway. (Which we should fix if is the case)

**Comment by pivanov** [comment]
You mean https://github.com/kite-project/hope/issues/25 right?

**Comment by jonathanKingston** [comment]
Nah I meant the CSS you indented: `#windows .appWindow.homescreen` I'm not sure if it applies to the latest code on Android. I was going to yank it out but I think it only applies to Android builds.

**Pull request merged**
