### PR TITLE
Make the tabs remote for real.

### LINKED ISSUE #48: The hope-tab's iframes are not really remote
good news is, it probably explains most of the performance issue we have.
bad news is, it might be tricky to fix.

But when watching `b2g-ps` with hope or with classic gaia you can definitely see that we're not creating new processes for tabs.

### PR DESCRIPTION
**Pull request by etiennesegonzac**
Fixes #48 .

### CODE REVIEW

**Comment by etiennesegonzac** [comment]
Apparently the html5-style attribute wasn't getting picked up.
Also had to change the event from `load` to `mozbrowserloadend` similarly to what the gaia system app does.
Added a safety timeout since we'll probably have frames loading remote content going through this path ("open in new tab" use-case).

Tested it for the addon and the b2gdroid build. Both work **way** better.

@jonathanKingston care to do a small review?

**Comment by jonathanKingston** [comment]
So the only issue I can see right now is it appears the new tab screen won't load under this setup. I'll try doing a quick dig now if I can find why that is... I suspect it was that the permissions are impacted with this new tab settings.

**Comment by jonathanKingston** [comment]
I'm a little bit worried by the inconsistent handling of `remote` as removing it means adding a new tab displays the correct code however the first page load appears fine with and without `remote`. This to me implies on first execute of the `index.html` is all in a single content process.

Anyway perhaps perhaps there is a simple fix here, right now I can't immediately see it and need some sleep.

**Comment by jonathanKingston** [comment]
Certainly feels a whole lot more stable with remote tabs though :smile:

**Comment by etiennesegonzac** [comment]
Can't reproduce the issue... this is getting weirder and weirder....
How are you pushing hope on the device?

**Comment by jonathanKingston** [comment]
WebIDE through dev edition Firefox on Ubuntu.
It can't be anything like that as normal first tab works but adding a new
tab doesn't load the new tab screen.

**Comment by etiennesegonzac** [comment]
> WebIDE through dev edition Firefox on Ubuntu. It can't be anything like that as normal first tab works but adding a new tab doesn't load the new tab screen.

On b2g phone? On an android phone with b2gdroid?

Because, we support
- the "WebExtension-ish" addon on b2g phone
- a custom b2gdroid build using hope as a system app 

But we probably don't want to support a WebExtension on top of the classic b2gdroid builds if it doesn't work out of the box.

**Comment by jonathanKingston** [comment]
b2g phone, I use a Z3 with an fxp community build.
It seems to work for everything besides that, however will do some further
debugging tonight.

**Comment by jonathanKingston** [comment]
I recorded the whitescreen of death issue here the framerate is laggy so not indicative of device perf:
https://vimeo.com/154941596

After merging this with the homescreen button fix #51, I get nothing on the console whilst this is happening in terms of exceptions. (Will try with debug on tomorrow).

**Comment by etiennesegonzac** [comment]
Thanks. I'm really curious :)
Tried again with a rebased branch and a fresh npm install -> everything works fine.

**Comment by jonathanKingston** [comment]
I have been given a flame now I have joined so will check this out on there to see if the same issue exists... (just thought I would give you a heads up).

**Comment by etiennesegonzac** [comment]
Cool! Which team?

**Comment by jonathanKingston** [comment]
@etiennesegonzac the connected devices security team. I need to flash the flame but will get back to you about that :D. It could be my Z3 doesn't have e10s setup correctly or something.

**Comment by etiennesegonzac** [comment]
yeah I'll test with a fresh build here too.
in any case, welcome! :)

**Comment by jonathanKingston** [comment]
So seems the same on a Z3C foxfooding build too. Paul mentioned it could be a bug in addons themselves and wanted to walk me through the isolation code anyway.
As it's only a demo worth considering having an external URL serve the new tab page for the time being?
Feel free to find me on phonebook or IRC to chat about this :D

**Comment by jonathanKingston** [comment]
@etiennesegonzac - I think this is good to go now with the remote homescreen code if that is ok with you?

**Comment by etiennesegonzac** [comment]
Yep, let's merge this one so we can cleanly rebase #52  (if it's not already the case ;)

**Pull request merged**
