### PR TITLE
Remote homescreen

### PR DESCRIPTION
**Pull request by jonathanKingston**
For fixing the issue outlined in #49 and depends on that code. It also should be moved over to the kite-project name.

### CODE REVIEW

**Comment by jonathanKingston** [comment]
The test is failing on jshint however it's not on what I thought it would. The integration test checking if the homescreen url loaded doesn't seem to be passing.

Anyway I only submitted the patch as an idea, if it's going to happen then we can move the homescreen back into kite and fix the tests + urls.

**Comment by etiennesegonzac** [comment]
Can't believe this comment is being written in 2016 but...

Can you move hope-home to this org (you should have the permissions) + add support for AppCache? :)

This way we can easily setup demo devices by loading once, and we can do more build-time-stuff later to prefill the cache.

**Comment by jonathanKingston** [comment]
Baha sure. Sorry was at a meet up give me an hour :)

**Comment by jonathanKingston** [comment]
@etiennesegonzac apparently I need admin rights to the kite project to do that. Not sure if that is ok or there is another way to transfer (Feel free to downgrade after etc).

**Comment by etiennesegonzac** [comment]
Hey @jonathanKingston can you rebase/squash this one?

**Comment by jonathanKingston** [comment]
@etiennesegonzac pushed rebase :D

**Comment by etiennesegonzac** [comment]
:+1:

**Pull request merged**
